:stem: latexmath
:sectnums:
:toc: macro
:toclevels: 3

link:home[Back to Main Page]


[[sec.control.field_output]]

There are two routines that can be used to write out the field used in _opal-cycl_. 
....
DUMPFIELDS: write out static magnetic field map on a Cartesian grid
DUMPEMFIELDS: write out electromagnetic field map on a 4D grid in space-time
....

==== DUMPFIELDS Command

The `DUMPFIELDS` statement causes _opal-cycl_ to write out static magnetic field data on a 3D cartesian grid. The format of field output is:

....
<number of rows>
1 x [m]
2 y [m]
3 z [m]
4 Bx [kGauss]
5 By [kGauss]
6 Bz [kGauss]
0
<field map data>
....

The following attributes are enabled on the `DUMPFIELDS` statement:

X_START::
  Start point in the grid in x
DX::
  Grid step size in x
X_STEPS::
  Number of steps in x
Y_START::
  Start point in the grid in y
DY::
  Grid step size in y
Y_STEPS::
  Number of steps in y
Z_START::
  Start point in the grid in z
DZ::
  Grid step size in z
Z_STEPS::
  Number of steps in z
FILE_NAME::
  Name of the file to which field data is dumped

This example makes a field map in the midplane (x-y plane) only, starting at _(x,y)_ = (0,0)_ m, with 101 steps in each direction and a stride of 0.1 m. _z_ is always 0.
....
DUMPFIELDS, X_START=0., X_STEPS=101, DX=0.100,
            Y_START=0., Y_STEPS=101, DY=0.100, 
            Z_START=0., Z_STEPS=1, DZ=0.100, 
            FILE_NAME="FieldMapXY.dat";

....


==== DUMPEMFIELDS Command


The `DUMPEMFIELDS` statement causes _opal-cycl_ to write out electromagnetic field data on a 4D cartesian grid. The format of field output is:
