:stem: latexmath
:sectnums:
:toc: macro
:toclevels: 3

link:home[Back to Main Page]


[[sec.control.field_output]]

There are two routines that can be used to write out the field used in _opal-cycl_. 
....
DUMPFIELDS: write out static magnetic field map on a Cartesian grid
DUMPEMFIELDS: write out electromagnetic field map on a 4D grid in space-time
....

==== DUMPFIELDS Command

The `DUMPFIELDS` statement causes _opal-cycl_ to write out static magnetic field data on a 3D cartesian grid. The format of field output is:

....
<number of rows>
<column 1> <units>
<column 2> <units>
<column 3> <units>
<column 4> <units>
<column 5> <units>
<column 6> <units>
0
<field map data>
....

The `DUMPFIELDS` statement takes a number of parameters:
X_START::
  Start point in the grid in x [m]
DX::
  Grid step size in x [m]


X_STEPS;                // Number of steps in x
FILE_NAME;              // Name of the file to which field data is dumped

`label` is an identifier see link:format#sec.format.label[Identifiers or Labels]. If it is non-blank, _OPAL_
displays the object `label` in a format similar to the input statement
that created the object. Entering `WHAT` alone displays help on the
`WHAT` command. Examples:

....
WHAT;
WHAT,NAME=QD;
WHAT,QD;
....




