= The OPAL Framework
Andreas Adelmann, Christian Baumgarten, Matthias Frey, Achim Gsell, Valeria Rizzoglio, Jochem Snuverink (PSI) Christof Metzger-Kraus, Yves Ineichen, Xiaoying Pang, Steve Russell (LANL), Chuan Wang (CIAE), Suzanne Sheehy, Chris Rogers (RAL) and Daniel Winklehner (MIT)
Version 2.0, June 2018: 1. revision

ifdef::env-gitlab[]
*Object Oriented Parallel Accelerator Library*

*_OPAL_ 2.0.0 User's Reference Manual*
endif::[]

ifdef::backend-docbook5[]
:numbered:
:toc:                                                               
:description: _OPAL_ User Manual                             
:keywords: _OPAL_
endif::[]


== Abstract

_OPAL_ is a tool for charged-particle optics in accelerator structures
and beam lines. Using the _MAD_ language with extensions, _OPAL_ is
derived from _MAD9P_ and is based on the _CLASSIC_ class library, which
was started in 1995 by an international collaboration. IPPL (Independent
Parallel Particle Layer) is the framework which provides parallel
particles and fields using data parallel ansatz. IPPL was inspired by the POOMA. _OPAL_ is built from
the ground up as a parallel application exemplifying the fact that HPC
(High Performance Computing) is the third leg of science, complementing
theory and the experiment. HPC is made possible now through the
increasingly sophisticated mathematical models and evolving computer
power available on the desktop and in super computer centres. _OPAL_
runs on your laptop as well as on the largest HPC clusters available
today.

The _OPAL_ framework makes it easy to add new features in the form of
new _C++_ classes. It comes in the following flavours:

* _OPAL-cycl_:
  tracks particles with 3D space charge including neighbouring turns in
  cyclotrons and FFAs with time as the independent variable.
* _OPAL-t_:
  can be used to model beam lines, linacs, rf-photo injectors and
  complete XFELs excluding the undulator.

It should be noted that not all features of _OPAL_ are available in all
flavours. The icon `DOPAL-t` means that a feature is not yet available
in _OPAL-t_. Similar icons are used for the other flavours.

ifdef::env-gitlab[]
== Table of Contents

. link:introduction[Introduction]
. link:conventions[Conventions]
. link:pitfalls[Pitfalls and Limitations]
. link:tutorial[Tutorial]
. link:opalt[OPAL-T]
. link:opalcycl[OPAL-CYCL]
. link:format[Command Format]
. link:control[Control Statements]
. link:elements[Elements]
. link:field-output[Field Output Commands]
. link:lines[Beam Lines]
. link:beam-command[Beam Command]
. link:distribution[Distribution Command]
. link:fieldsolvers[Field Solver]
. link:track[Tracking]
. link:wakefields[Wakefields]
. link:geometry[Geometry]
. link:partmatter[Physics Models Used in the Particle Matter Interaction Model]
. link:optimiser[Multi Objective Optimization]
. link:sampler[Sampler]

.Appendices
[upperalpha]
. link:syntax[OPAL Language Syntax]
. link:fieldmaps[OPAL-T Field Maps]
. link:opal-madx[OPAL-MADX Conversion Guide]
. link:autophase[Auto-phasing Algorithm]
. link:benchmarks[Benchmarks]
. https://gitlab.psi.ch/OPAL/src/wikis/opaldks[Dynamic Kernel Scheduler (DKS)]

link:fieldsolvers#chp.fieldsolvers[Field Solver]

endif::[]

ifdef::backend-docbook5[]
include::introduction.adoc[]

include::conventions.adoc[]

include::pitfalls.adoc[]

include::tutorial.adoc[]

include::opalt.adoc[]

include::opalcycl.adoc[]

include::format.adoc[]

include::control.adoc[]

include::elements.adoc[]

include::field-output.adoc[]

include::lines.adoc[]

include::beam-command.adoc[]

include::distribution.adoc[]

include::fieldsolvers.adoc[]

include::track.adoc[]

include::wakefields.adoc[]

include::geometry.adoc[]

include::partmatter.adoc[]

include::optimiser.adoc[]

include::sampler.adoc[]

include::syntax.adoc[]

include::fieldmaps.adoc[]

include::opal-madx.adoc[]

include::autophase.adoc[]

include::benchmarks.adoc[]
endif::[]
