---
title: "Build and Developer Resources"
---

## Download of Binaries and Clone of Repository

| Version / source code | Linux binary package | macOS binary package | Manual | Source code documentation | Release notes |
|---|---|---|---|---|---|
| `OPAL` development | n.a. | n.a. | [HTML](https://opalx-project.github.io/opal-manual/) | [HTML](https://opalx-project.github.io/OPAL/) | n.a. |
| [`OPAL 2024.1.0`](https://github.com/OPALX-project/OPAL/releases/download/OPAL-2024.1.0/OPAL-2024.1.0.tar.xz) |  |  |  | [HTML](https://opalx-project.github.io/OPAL/) | [Release notes 2024.1](https://opalx-project.github.io/ReleaseNotes/OPAL-2024.1.html) |
| [`OPAL 2022.1.0`](https://github.com/OPALX-project/OPAL/releases/download/OPAL-2022.1.0/OPAL-2022.1.0.tar.xz) | [tar.xz](https://github.com/OPALX-project/OPAL/releases/download/OPAL-2022.1.0/OPAL-2022.1.0-1-x86_64-linux.tar.xz) | [tar.xz (x86_64)](https://github.com/OPALX-project/OPAL/releases/download/OPAL-2022.1.0/OPAL-2022.1.0-1-x86_64-macos.tar.xz), [tar.xz (M1)](https://github.com/OPALX-project/OPAL/releases/download/OPAL-2022.1.0/OPAL-2022.1.0-1-arm-macos.tar.xz) |  | [HTML](https://opalx-project.github.io/OPAL/) | [Release notes 2022.1](https://opalx-project.github.io/ReleaseNotes/OPAL-2022.1.html) |
| [`OPAL 2021.1.0`](https://github.com/OPALX-project/OPAL/releases/download/OPAL-2021.1.0/OPAL-2021.1.0.tar.xz) | [tar.xz](https://github.com/OPALX-project/OPAL/releases/download/OPAL-2021.1.0/OPAL-2021.1.0-1-x86_64-linux.tar.xz) | [tar.xz (x86_64)](https://github.com/OPALX-project/OPAL/releases/download/OPAL-2021.1.0/OPAL-2021.1.0-1-x86_64-macos.tar.xz) |  | [HTML](https://opalx-project.github.io/OPAL/) | [Release notes 2021.1](https://opalx-project.github.io/ReleaseNotes/OPAL-2021.1.html) |

Instead of downloading a source tarball, you can clone the full repository with:

```sh
git clone https://github.com/OPALX-project/OPAL.git
```

Or clone a specific branch or tag with:

```sh
git clone --single-branch --depth 1 --branch BRANCH_OR_TAG https://github.com/OPALX-project/OPAL.git [DIR]
```

For older releases, see the [OPAL GitHub releases page](https://github.com/OPALX-project/OPAL/releases).

## Compiling

For `OPAL`, the standard build instructions are:

- [Supported OS and required software to build OPAL](https://opalx-project.github.io/For-Developers/Supported-OS-and-required-Software-to-build-OPAL.html)
- [Setup build environment at PSI](https://opalx-project.github.io/For-Developers/Setup-build-environment-at-PSI.html)
- [Compile required software](https://opalx-project.github.io/For-Developers/Compile-required-software.html)
- [Compile OPAL](https://opalx-project.github.io/For-Developers/Compile-OPAL.html)
- [Compile OPAL at CSCS](https://opalx-project.github.io/For-Developers/Compile-OPAL-at-CSCS.html)

## Developer Resources

For `OPAL`, the linked developer resources are:

- [Coding Style and conventions](https://opalx-project.github.io/For-Developers/CodingStyle.html)
- [Building, executing, and writing unit tests](https://opalx-project.github.io/For-Developers/unit-tests.html)
- [Development workflow](https://opalx-project.github.io/For-Developers/OPAL-Development-Workflow.html)
- [Release procedure](https://opalx-project.github.io/For-Developers/Release-Procedure.html)
- [OPAL Doxygen](https://opalx-project.github.io/OPAL/)
- [Regression-test repository](https://github.com/OPALX-project/regression-tests)
- [Regression tests](https://github.com/OPALX-project/regression-tests/tree/master/RegressionTests)
- [Unit tests](https://github.com/OPALX-project/OPAL/tree/master/tests)

## Source Repositories and Issue Trackers

The main source repositories and issue trackers are:

- [OPAL repository](https://github.com/OPALX-project/OPAL)
- [OPAL issue tracker](https://github.com/OPALX-project/OPAL/issues)
- [OPAL regression-test repository](https://github.com/OPALX-project/regression-tests)
