name: Build Manual

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write       # to deploy to Pages
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python HTML tooling
        run: |
          python3 -m pip install beautifulsoup4

      - name: Build Quarto Manual
        run: |
          quarto render . --to html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs-quarto

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
